Very smool change
Cryptex-github/the-anime-bot-bot pull request #105
Opened 2021-06-20 03:47 UTC by Sitanshu-15

Increase number of "quotes"

2021-06-20 04:17 UTC, Cryptex-github requested changes

2021-06-20 04:17 UTC, Cryptex-github commented on cogs/anime.py
> +        num = random.randint(1, 8674)
let me increase it more then

2021-06-20 04:18 UTC, Cryptex-github approved these changes

2021-06-20 04:18 UTC, merged

2021-06-22 13:01 UTC, Sitanshu-15 commented on cogs/anime.py
> +        num = random.randint(1, 8674)
ye you can do that sure.

2021-06-22 13:02 UTC, Sitanshu-15 commented on cogs/anime.py
> +        num = random.randint(1, 8674)
+ I think there is a better way using a web scrapper but that would be a lil too much.